services:
  tts:
    image: soar97/triton-f5-tts:24.12
    shm_size: '2gb'
    ports:
      - "9000:8000"
      - "9001:8001"
      - "9002:8002"
    environment:
      - PYTHONIOENCODING=utf-8
      - MODEL=${MODEL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: >
      /bin/bash -c "pip install vocos && rm -rf F5-TTS && git clone https://github.com/Adriel2503/F5_Esp_TTS.git && cd F5_Esp_TTS/src/f5_tts/runtime/triton_trtllm/ && bash run.sh 0 4 $MODEL"
